"use client";

import { useState } from "react";
import { ConnectionType, ConnectionStyles } from "@/lib/canvas/types";
import { useCanvasStore } from "@/lib/canvas/store";
import { Link2, Sparkles, Palette, ArrowRight, X } from "lucide-react";

interface ConnectionTypeSelectorProps {
  edgeId: string;
  position: { x: number; y: number };
  onClose: () => void;
}

const CONNECTION_OPTIONS: Array<{
  type: ConnectionType;
  label: string;
  description: string;
  icon: typeof Link2;
}> = [
  {
    type: "reference",
    label: "Reference",
    description: "Use as general reference",
    icon: Link2,
  },
  {
    type: "ai-input",
    label: "AI Input",
    description: "Feed into AI as context",
    icon: Sparkles,
  },
  {
    type: "ai-output",
    label: "AI Output",
    description: "Generated by AI",
    icon: ArrowRight,
  },
  {
    type: "inspiration",
    label: "Inspiration",
    description: "Visual inspiration source",
    icon: Palette,
  },
  {
    type: "style-source",
    label: "Style Source",
    description: "Copy style from this",
    icon: Palette,
  },
];

export function ConnectionTypeSelector({
  edgeId,
  position,
  onClose,
}: ConnectionTypeSelectorProps) {
  const { updateEdge, edges } = useCanvasStore();
  
  const edge = edges.find((e) => e.id === edgeId);
  const currentType = edge?.data?.connectionType || "reference";

  const handleSelect = (type: ConnectionType) => {
    const style = ConnectionStyles[type];
    updateEdge(edgeId, {
      connectionType: type,
      color: style.color,
      style: style.style,
      label: style.label,
      animated: type === "ai-input" || type === "ai-output",
    });
    onClose();
  };

  // Adjust position to stay in viewport
  const adjustedPosition = {
    x: Math.min(position.x, window.innerWidth - 250),
    y: Math.min(position.y, window.innerHeight - 350),
  };

  return (
    <div
      className="fixed bg-white rounded-xl shadow-xl border py-2 w-56 z-50"
      style={{ left: adjustedPosition.x, top: adjustedPosition.y }}
    >
      {/* Header */}
      <div className="flex items-center justify-between px-3 py-1.5 border-b mb-1">
        <span className="text-xs font-medium text-gray-700">Connection Type</span>
        <button
          type="button"
          onClick={onClose}
          className="p-0.5 hover:bg-gray-100 rounded"
        >
          <X className="h-3.5 w-3.5 text-gray-400" />
        </button>
      </div>

      {/* Options */}
      {CONNECTION_OPTIONS.map((option) => {
        const Icon = option.icon;
        const style = ConnectionStyles[option.type];
        const isSelected = currentType === option.type;

        return (
          <button
            key={option.type}
            type="button"
            onClick={() => handleSelect(option.type)}
            className={`w-full flex items-center gap-3 px-3 py-2 text-left transition-colors ${
              isSelected ? "bg-gray-100" : "hover:bg-gray-50"
            }`}
          >
            <div
              className="w-8 h-8 rounded-lg flex items-center justify-center"
              style={{ backgroundColor: `${style.color}15` }}
            >
              <Icon className="h-4 w-4" style={{ color: style.color }} />
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-sm font-medium text-gray-700">{option.label}</p>
              <p className="text-[10px] text-gray-400">{option.description}</p>
            </div>
            {isSelected && (
              <div
                className="w-2 h-2 rounded-full"
                style={{ backgroundColor: style.color }}
              />
            )}
          </button>
        );
      })}

      {/* Preview */}
      <div className="px-3 pt-2 mt-1 border-t">
        <p className="text-[10px] text-gray-400 mb-2">Preview</p>
        <div className="flex items-center gap-2">
          <div className="w-8 h-1 bg-gray-200 rounded" />
          <div
            className="flex-1 h-0.5 rounded"
            style={{
              backgroundColor: ConnectionStyles[currentType].color,
              borderStyle: ConnectionStyles[currentType].style === "dashed" ? "dashed" : 
                          ConnectionStyles[currentType].style === "dotted" ? "dotted" : "solid",
            }}
          />
          <div className="w-8 h-1 bg-gray-200 rounded" />
        </div>
      </div>
    </div>
  );
}

export default ConnectionTypeSelector;
