// Canvas Type Definitions for Spatial AI Canvas System
// Inspired by Eden.so - Surpassing Notion's limitations

import { Node, Edge, XYPosition } from 'reactflow';

// ============================================================================
// CORE CANVAS TYPES
// ============================================================================

export type NodeType = 
  | 'image' 
  | 'video' 
  | 'document' 
  | 'note' 
  | 'ai-chat' 
  | 'ai-generator' 
  | 'group'
  | 'audio'
  | 'url';

export type ConnectionType = 
  | 'reference'      // Used as reference/inspiration
  | 'ai-input'       // Input to AI
  | 'ai-output'      // Generated by AI
  | 'inspiration'    // Loose inspiration
  | 'style-source';  // Style reference

export interface BaseNodeData {
  label: string;
  createdAt: Date;
  updatedAt: Date;
  userId: string;
  metadata?: Record<string, unknown>;
  tags?: string[];
  aiTags?: string[];
  isLocked?: boolean;
  description?: string;
}

// ============================================================================
// SPECIFIC NODE DATA TYPES
// ============================================================================

export interface ImageNodeData extends BaseNodeData {
  type: 'image';
  url: string;
  thumbnail?: string;
  width: number;
  height: number;
  fileSize: number;
  mimeType: string;
  mediaLibraryId?: string;
  aiAnalysis?: {
    objects: string[];
    colors: string[];
    style: string[];
    composition: string;
    mood: string;
  };
  exif?: Record<string, unknown>;
}

export interface VideoNodeData extends BaseNodeData {
  type: 'video';
  url: string;
  thumbnail?: string;
  duration: number;
  width: number;
  height: number;
  fileSize: number;
  transcription?: {
    text: string;
    timestamps: Array<{ time: number; text: string }>;
  };
  scenes?: Array<{
    timestamp: number;
    thumbnail: string;
    description: string;
  }>;
  mediaLibraryId?: string;
}

export interface DocumentNodeData extends BaseNodeData {
  type: 'document';
  url: string;
  fileType: 'pdf' | 'docx' | 'txt' | 'md';
  pageCount?: number;
  extractedText?: string;
  summary?: string;
  mediaLibraryId?: string;
}

export interface NoteNodeData extends BaseNodeData {
  type: 'note';
  content: string; // TipTap JSON or HTML
  backgroundColor?: string;
  textColor?: string;
  fontSize?: 'small' | 'medium' | 'large';
  isPinned?: boolean;
}

export interface UrlNodeData extends BaseNodeData {
  type: 'url';
  url: string;
  title?: string;
  description?: string;
  thumbnail?: string;
  favicon?: string;
  siteName?: string;
}

export interface AIChatNodeData extends BaseNodeData {
  type: 'ai-chat';
  model: AIModel;
  conversation: Message[];
  connectedAssetIds: string[];
  systemPrompt?: string;
  temperature?: number;
  maxTokens?: number;
  isExpanded: boolean;
  contextSummary?: string;
}

export interface AIGeneratorNodeData extends BaseNodeData {
  type: 'ai-generator';
  provider: AIImageProvider;
  prompt: string;
  negativePrompt?: string;
  referenceImageIds: string[];
  parameters: GenerationParameters;
  generationHistory: GeneratedImage[];
  status: 'idle' | 'generating' | 'completed' | 'error';
  error?: string;
  currentJobId?: string;
}

export interface GroupNodeData extends BaseNodeData {
  type: 'group';
  childNodeIds: string[];
  backgroundColor?: string;
  borderColor?: string;
  isCollapsed?: boolean;
}

export interface AudioNodeData extends BaseNodeData {
  type: 'audio';
  url: string;
  duration: number;
  waveform?: number[];
  transcription?: string;
  mediaLibraryId?: string;
}

// Union type for all node data types
export type CanvasNodeData = 
  | ImageNodeData 
  | VideoNodeData 
  | DocumentNodeData 
  | NoteNodeData 
  | UrlNodeData
  | AIChatNodeData 
  | AIGeneratorNodeData 
  | GroupNodeData
  | AudioNodeData;

// ============================================================================
// AI TYPES
// ============================================================================

export type AIModel = 
  | 'claude-sonnet-4' 
  | 'claude-opus-4'
  | 'gpt-4-turbo' 
  | 'gpt-4' 
  | 'gpt-4o'
  | 'gemini-pro'
  | 'gemini-2.0-flash';

export type AIImageProvider = 
  | 'dalle-3' 
  | 'midjourney' 
  | 'stable-diffusion-xl'
  | 'flux-pro'
  | 'flux-dev'
  | 'imagen';

export interface Message {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: Date;
  attachments?: Array<{
    type: 'image' | 'document';
    nodeId: string;
    url: string;
  }>;
}

export interface GenerationParameters {
  aspectRatio: '1:1' | '16:9' | '4:3' | '9:16' | '3:2' | '2:3';
  quality: 'standard' | 'hd' | 'ultra';
  style?: string;
  numberOfImages?: number;
  seed?: number;
  guidance?: number;
  steps?: number;
}

export interface GeneratedImage {
  id: string;
  url: string;
  thumbnail?: string;
  prompt: string;
  revisedPrompt?: string;
  provider: AIImageProvider;
  parameters: GenerationParameters;
  timestamp: Date;
  width: number;
  height: number;
  seed?: number;
  inCanvas: boolean;
  savedToLibrary: boolean;
  mediaLibraryId?: string;
}

// ============================================================================
// CONNECTION/EDGE TYPES
// ============================================================================

export interface CanvasConnectionData {
  label?: string;
  color?: string;
  style?: 'solid' | 'dashed' | 'dotted';
  animated?: boolean;
  strength?: number;
  connectionType?: ConnectionType;
  metadata?: Record<string, unknown>;
}

export type CanvasConnection = Edge<CanvasConnectionData>;

// ============================================================================
// CANVAS NODE (React Flow Node wrapper)
// ============================================================================

export type CanvasNode = Node<CanvasNodeData>;

// ============================================================================
// CANVAS STATE
// ============================================================================

export interface CanvasState {
  workspaceId: string;
  canvasId: string;
  nodes: CanvasNode[];
  edges: CanvasConnection[];
  viewport: {
    x: number;
    y: number;
    zoom: number;
  };
  selectedNodeIds: string[];
  copiedNodes?: CanvasNode[];
  isLoading: boolean;
  isSaving: boolean;
  lastSaved?: Date;
  collaborators: Collaborator[];
  version: number;
  metadata: CanvasMetadata;
}

export interface CanvasMetadata {
  name: string;
  description?: string;
  thumbnail?: string;
  tags: string[];
  category?: string;
  isPublic: boolean;
}

// ============================================================================
// COLLABORATION TYPES
// ============================================================================

export interface Collaborator {
  userId: string;
  userName: string;
  userAvatar?: string;
  color: string;
  cursor?: XYPosition;
  selectedNodeIds: string[];
  isActive: boolean;
  lastSeen: Date;
}

export interface CollaborationEvent {
  type: 'cursor-move' | 'node-update' | 'node-add' | 'node-delete' | 'edge-add' | 'edge-delete' | 'selection-change';
  userId: string;
  timestamp: Date;
  data: unknown;
}

// ============================================================================
// LAYOUT & SMART FEATURES
// ============================================================================

export enum LayoutStyle {
  GRID = 'grid',
  RADIAL = 'radial',
  TIMELINE = 'timeline',
  STORYBOARD = 'storyboard',
  CLUSTER = 'cluster',
  FORCE_DIRECTED = 'force-directed'
}

export interface LayoutOptions {
  style: LayoutStyle;
  spacing: number;
  padding: number;
  animate: boolean;
  duration?: number;
  centerPosition?: XYPosition;
}

export interface AIContextData {
  images: Array<{
    nodeId: string;
    url: string;
    analysis: string;
  }>;
  documents: Array<{
    nodeId: string;
    summary: string;
    keyPoints: string[];
  }>;
  notes: Array<{
    nodeId: string;
    content: string;
  }>;
  previousGenerations: GeneratedImage[];
  styleKeywords: string[];
  topics: string[];
  mood?: string;
  colorPalette?: string[];
}

// ============================================================================
// CANVAS TEMPLATES
// ============================================================================

export interface CanvasTemplate {
  id: string;
  name: string;
  description: string;
  thumbnail?: string;
  category: string;
  tags: string[];
  nodes: Partial<CanvasNode>[];
  edges: Partial<CanvasConnection>[];
  instructions?: string;
  useCases: string[];
  createdBy: string;
  isPublic: boolean;
  usageCount: number;
}

// ============================================================================
// EXPORT & IMPORT
// ============================================================================

export interface CanvasExport {
  version: string;
  exportDate: Date;
  canvas: {
    metadata: CanvasMetadata;
    nodes: CanvasNode[];
    edges: CanvasConnection[];
  };
  assets: Array<{
    nodeId: string;
    type: 'image' | 'video' | 'document';
    blob?: Blob;
    url: string;
  }>;
}

// ============================================================================
// STYLE ANALYSIS (for Style Transfer)
// ============================================================================

export interface StyleAnalysis {
  composition: string;
  colorPalette: string[];
  lighting: string;
  mood: string;
  techniques: string[];
  styleKeywords: string[];
  detailedDescription: string;
}

// ============================================================================
// BATCH GENERATION
// ============================================================================

export interface BatchGenerationJob {
  id: string;
  prompts: string[];
  provider: AIImageProvider;
  parameters: GenerationParameters;
  status: 'pending' | 'processing' | 'completed' | 'error';
  progress: number;
  results: GeneratedImage[];
  errors: string[];
  createdAt: Date;
  completedAt?: Date;
}

// ============================================================================
// CONNECTION STYLING PRESETS
// ============================================================================

export const ConnectionStyles: Record<ConnectionType, { color: string; style: 'solid' | 'dashed' | 'dotted'; label: string }> = {
  'ai-input': {
    color: '#3B82F6', // Blue
    style: 'solid',
    label: 'As Reference'
  },
  'ai-output': {
    color: '#10B981', // Green
    style: 'dashed',
    label: 'Generated by AI'
  },
  'inspiration': {
    color: '#F59E0B', // Orange
    style: 'dotted',
    label: 'Inspiration'
  },
  'reference': {
    color: '#8B5CF6', // Purple
    style: 'solid',
    label: 'Reference'
  },
  'style-source': {
    color: '#EC4899', // Pink
    style: 'solid',
    label: 'Style Source'
  }
};

// ============================================================================
// NODE SIZE DEFAULTS
// ============================================================================

export const NodeSizeDefaults: Record<NodeType, { width: number; height: number }> = {
  'image': { width: 280, height: 200 },
  'video': { width: 320, height: 240 },
  'document': { width: 240, height: 180 },
  'note': { width: 240, height: 160 },
  'ai-chat': { width: 360, height: 400 },
  'ai-generator': { width: 340, height: 380 },
  'group': { width: 400, height: 300 },
  'audio': { width: 280, height: 100 },
  'url': { width: 280, height: 160 }
};
